# Generated by Django 4.0 on 2022-01-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coustomer',
            new_name='Customer',
        ),
    ]
