# Generated by Django 4.0 on 2022-01-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
